# Generated by Django 3.2.4 on 2021-07-07 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0003_auto_20210707_0312'),
        ('news', '0002_newspost_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='ad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='advertising.ad'),
        ),
    ]
