# Generated by Django 3.2.4 on 2021-07-07 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('copy', models.TextField(max_length=2000)),
                ('logo', models.FileField(max_length=200, upload_to='')),
                ('url', models.URLField()),
            ],
        ),
    ]
