# Generated by Django 3.2.4 on 2021-07-07 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='logo',
            field=models.ImageField(max_length=200, upload_to=''),
        ),
    ]
