# Generated by Django 3.2.4 on 2021-07-07 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0002_alter_ad_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='house_ad',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ad',
            name='logo',
            field=models.ImageField(max_length=200, upload_to='static/uploads/'),
        ),
    ]
